version: '3.7'

networks:
    internet:
        driver: bridge

services: 

    zphisher:

        container_name: social-hcker
        
        build: .
        image: social-hacker:v0.1
        command: bash hack.sh
        stdin_open: true
        tty: true
        volumes: 
            - $PWD/websites:/home/websites
        networks: 
            - internet
        restart: always
